import { Roboto_Mono } from "next/font/google";
import "./globals.css";
import { HeroContextProvider } from "@/utils/contextProvider";
const roboto = Roboto_Mono({ weight: "400", subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <HeroContextProvider>{children}</HeroContextProvider>
      </body>
    </html>
  );
}
