import localFont from 'next/font/local'

import "./globals.css";
const cascadia = localFont({
  src: [
    {
      path: './fonts/CascadiaCode.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/CascadiaCodeItalic.woff2',
      weight: '400',
      style: 'italic',
    },

    {
      path: './fonts/CascadiaMono.woff2',
      weight: '700',
      style: 'mono',
    },
  ],
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cascadia.className}>{children}</body>
    </html>
  );
}
